name = "family-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
NUXT_PUBLIC_VAPID_PUBLIC_KEY = "BMurhLl5RIhNqnh1klwkCEo28u9rVvhaG96ig_PBp3Kun3pLZTLKfV4sC2YYXQ9on-si7zA5JaO0MGzDGZVXr-8"
